from . import patient_survey
from . import res_config
from . import res_company
from . import diagnosis
from . import insurance
from . import res_partner
from . import product
from . import medicament
from . import physician
from . import occupation
from . import website
from . import patient
from . import nationality
from . import medication
from . import appointment
from . import hospital_units
from . import teeth_code
from . import chart_selection
from . import product_category
from . import medical_teeth_treatment
from . import patient_complaint
from . import attachment
from . import patient_feedback
from . import prescription
from . import complaint_finding
from . import operation_summary
from . import treatment_invoice
from . import invoice
from . import treatment_plan_wizard
from . import patient_registration
from . import sign_wizard
from . import treatment_sign_wizard
from . import dashboard
from . import prescription_additional
from . import res_users
from . import account_move
from . import config_settings