# -*- encoding: utf-8 -*-
{

    'name': 'Odoo - Medical Management',
    'version': '11.0',
    'author': 'Al Kidhma Group',
    'sequence': 2,
    'category': 'Generic Modules/Others',
    'depends': ['base', 'website', 'sale_management', 'purchase', 'account', 'product', 'account_invoicing',
                'document', 'google_calendar', 'product_expiry', 'web', 'report_letterhead',
                'web_domain_field',
                'web_notify',
                'contacts',
                'sales_team',
                'crm',
                'web_digital_sign',
                'web_tree_image',
                'account_cancel',
                'invoice_discount_solution',
                'account_cost_center',
                ],
    'description': """
This modules includes Medical Management Features
""",
    'website': '',
    "data": [
        'security/dental_security.xml',
        'security/multi_company_security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/dental_data.xml',
        'data/dose_units.xml',
        'data/medicament_form.xml',
        'data/snomed_frequencies.xml',
        'data/occupations.xml',
        'data/teeth_code.xml',
        'views/res_config_views.xml',
        'views/attachments.xml',
        'views/treatment_plan.xml',
        'views/dental_view.xml',
        'wizard/archive_wizard.xml',
        'wizard/edit_patient.xml',
        'wizard/completed_reversal.xml',
        'wizard/wizard_actions.xml',
        'views/dental_sequences.xml',
        'report/income_by_procedure_qweb.xml',
        'report/patient_by_procedure_qweb.xml',
        'views/res_company.xml',
        'views/dental_report.xml',
        'views/config_settings.xml',
        'report/report_appointment.xml',
        'report/report_patient_visit.xml',
        'views/templates.xml',
        'report/report_income_by_procedure.xml',
        'report/report_patient_by_procedure.xml',
        'report/account_invoice_report_view.xml',
        'report/report_income_by_doctor.xml',
        'report/report_patient_by_doctor.xml',
        'views/diagnosis.xml',
        'wizard/setting.xml',

        'views/patient_feedback.xml',
        'views/patient_feedback_wizard.xml',
        'report/prescription_report.xml',
        'report/prescription_additional_report.xml',
        'views/prescription.xml',
        'views/prescription_additional.xml',
        'views/patient.xml',
        'views/my_patients.xml',
        'views/treatment_invoice.xml',
        'views/invoices.xml',
        'report/patient_registration_template.xml',
        'report/patient_registration.xml',
        'report/patient_invoice_report.xml',

        'views/questionnaire_format.xml',
        'wizard/questionnaire_format_wizard.xml',
        'wizard/patient_overdue_report.xml',
        'report/report_patient_overdue.xml',
        'wizard/doctor_appointment_report.xml',
        'wizard/appointment_cancel_report.xml',
        'report/report_doctor_appointment.xml',
        'report/report_appt_cancellation.xml',
        'views/sign_wizard.xml',
        'views/treatment_sign_wizard.xml',

        'data/dashboard_data.xml',
        'views/dashboard_view.xml',
        'wizard/user_creation.xml',
        'views/res_users.xml',
    ],
    'active': False,
    'images': ['images/main_screenshot.png'],
    'qweb': [
        'static/src/xml/perio_base.xml',
        'static/src/xml/colorwidget.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
